# Generated by Django 4.2.2 on 2023-06-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
