# Generated by Django 4.2.2 on 2023-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_data_created_card_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='box',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
